composer:
  image: composer:latest
  container_name: composer
  working_dir: /code

webserver:
  image: nginx:alpine
  ports:
    - "80:80"
  volumes:
    - ./code:/srv/www/site
    - ./nginxphp.conf:/etc/nginx/conf.d/site.conf
  links:
    - php71
    
php71:
  build: ./phpfpm
  volumes:
    - ./code:/srv/www/site
  links:
    - db

db:
  image: mysql:5.6
  container_name: mysql
  working_dir: /application
  volumes:
    - ./data:/docker-entrypoint-initdb.d
    - mysqldata:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=xxx
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=test
    - MYSQL_PASSWORD=xxx
  ports:
    - "8084:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - "8081:80"
  links:
    - db